FROM quay.io/sampandey001/secktor
RUN git clone https://github.com/QUEENNICKYMDv1/QUEEN-NICKY-MD-V1- /root/moxie 
WORKDIR /root/moxie/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
